### ISSUE TITLE
[feature request] Rearranging the items

### ISSUE THREAD

**Issue by xyproto** [cgag/hostblock#7]
Hi,

I use hostblock daily. Thanks for creating it!

However, there are some sites I toggle more often than others. Could the hosts please be sorted on toggle frequency, possibly also with a key for moving a host up or down on the list?

Cheers!

-- Alexander

**Comment by cgag** [comment]
Glad you like it :)

Having keys to rearrange the items is a great idea, I'll definitely do that.  Do you have any thoughts on what the keys should be?  My first thought is J/K (shift j/shift k), but I used those for go to top/bottom, which I now kind of regret.  

Sorting them by frequency sounds interesting, but I personally have strong muscle / spacial memory built up, where I expect things to be in certain positions, I don't think I'd like things shifting over time.  Additionally it would require storing another file somewhere to hold the frequencies, which I'm not sure I'd want to introduce.

Thanks again for the feedback.

**Comment by xyproto** [comment]
Switching j/k over to moving items up and down, and using the arrow keys for moving the cursor, could be an option.

**Comment by xyproto** [comment]
About storing the toggle frequency, you might want to introduce a configuration file sooner or later anyways? Colors on/off, custom keybindings and automatic toggle off at lunch time? A man can dream.

**Comment by xyproto** [comment]
Thanks for considering this issue, closing because it's probably out of date by now.
